name: Build LaTeX documents
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Lang - Fundamentals of Differential Geometry/*.tex
            Munkres - Topology/*.tex
          glob_root_file: true
          work_in_root_file_dir: true
      - name: Upload PDFs
        uses: actions/upload-artifact@v2
        with:
          name: PDFs
          path: |
            Lang - Fundamentals of Differential Geometry/*.pdf
            Munkres - Topology/*.pdf