name: Build LaTeX documents
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Axler - Measure, Integration & Real Analysis/*.tex
            Hatcher - Algebraic Topology/*.tex
            Lang - Fundamentals of Differential Geometry/*.tex
            Mac Lane - Categories for the Working Mathematician/*.tex
            Munkres - Elements of Algebraic Topology/*.tex
            Munkres - Topology/*.tex
            Nakahara - Geometry, Topology and Physics/*.tex
            Olver - Applications of Lie Groups to Differential Equations/*.tex
            Rudin - Principles of Mathematical Analysis/*.tex
            Shilov - Linear Algebra/*.tex
            Sternberg - Lectures on Differential Geometry/*.tex
            Tu - Introduction to Manifolds/*.tex
          glob_root_file: true
          work_in_root_file_dir: true
      - name: Upload PDFs
        uses: actions/upload-artifact@v2
        with:
          name: PDFs
          path: |
            Axler - Measure, Integration & Real Analysis/*.pdf
            Hatcher - Algebraic Topology/*.pdf
            Lang - Fundamentals of Differential Geometry/*.pdf
            Mac Lane - Categories for the Working Mathematician/*.pdf
            Munkres - Elements of Algebraic Topology/*.pdf
            Munkres - Topology/*.pdf
            Nakahara - Geometry, Topology and Physics/*.pdf
            Olver - Applications of Lie Groups to Differential Equations/*.pdf
            Rudin - Principles of Mathematical Analysis/*.pdf
            Shilov - Linear Algebra/*.pdf
            Sternberg - Lectures on Differential Geometry/*.pdf
            Tu - Introduction to Manifolds/*.pdf